### ISSUE TITLE
Update lint to current DDA version

### ISSUE THREAD

**Issue by GuardianDll** [cdda-toys/cdda-json-formatter-vscode-extension#1]
https://github.com/CleverRaven/Cataclysm-DDA/pull/68683 added forced wrap to dda linting, but extension is still not aware of this change, and tries to lint ASCII art by default, like in https://github.com/CleverRaven/Cataclysm-DDA/pull/69161

**Comment by irwiss** [comment]
Thanks for filing the issue, I missed the linter change

I'm a bit busy irl so i'll likely only get to this on weekend, unless someone wants to tinker with it before then

**Comment by irwiss** [comment]
v1.0.8 should resolve this completely - i checked both valid json with picture field breaks down the lines and invalid json no longer prints color enum warning
